### PR TITLE
shlex everythig

### PR DESCRIPTION
**Pull request by jgirardet**

### CODE REVIEW

**Comment by jgirardet** [comment]
I miss something.
If you split first, How do you expand ?

**Comment by jgirardet** [comment]
_expand/expand_variables was confusing to me.
I'll look at it tomorrow or maybe next week.

**Comment by jgirardet** [comment]
Hi,
I was thinking to it seems that the thing is not so simple to do:

2 use cases about pytest parameter:
         a- /my folder/whit spaces/pytest # expandable
         b- poetry|pipenv|... run pytest #no expand should be needed

 Mix of two seems not very useful. depending the case you want to split space or not but it's not easy to guess.

 My proposal :
            - expand first
            - if path.is_file() --> do not split but turn to list ex ['my path with space/to/pytest'] # a-case
            - else: split ['my','command','line','pytest']  # b-case

**Comment by kaste** [comment]
Yes, you're correct. 

- 'pytest' can be a list of strings in which case we just expand.
- Otherwise, we want to support

  a) 'pytest.exe'
  b) 'C:\path to\my venvs\$project_name\Scripts\pytest'
  c) '$folder\Scripts\pytest'
  d) 'poetry run pytest'

For b and c we cannot split at all! Thanks for ppointing that out.

**Comment by kaste** [comment]
We also can't split `.\.venv\Scripts\pytest` (relative paths to the working dir). So, I suppose we just don't do it at all. Instead of 'poetry run pytest' users have to spell that `['poetry', 'run', 'pytest']` in the settings.

**Pull request closed without merging**
